### **WEB SCRAPING USING "BeautifulSoup"**

**Website link:<a href="/https://www.pararius.com/apartments/amsterdam?ac=1"> click here</a>**

In [107]:
from bs4 import BeautifulSoup
import requests
from csv import writer
from lxml.html.clean import Cleaner

url= "https://getlatka.com/saas-companies"
page = requests.get(url)
page1 = Cleaner(style=True).clean_html(page.content)
soup = BeautifulSoup(page1, 'html.parser')
lists = soup.find('table', class_="data-table_table__SwBLY")

# with open('getlatka.json' , 'w', encoding='utf8', newline='') as f:
with open('getlatka.csv' , 'w', encoding='utf8', newline='') as f:
    thewriter = writer(f)
    header = ["Name","Revenue","Funding","Valuation","Cash Flow","Founder","Team Size","Age (Yrs)","Location","Industry","Year"]
    thewriter.writerow(header)


    for list in lists.find_all('tbody'):
      rows = list.find_all('tr')
      for row in rows:
        title=row.find('a',class_='cells_link__PfQot').text
        rev=row.find('p').text
        fund=row.find_all('p')[1].text
        val=row.find_all('p')[2].text
        cashf=row.find('span').text
        fundr=row.find('a',class_="cells_name__pBrsJ").text
        teams=row.find_all('p')[3].text
        age=row.find_all('td')[8].text
        loc=row.find_all('a')[4].text
        industry =row.find_all('a')[5].text
        year=row.find_all('td')[11].text
        # print(title,rev,fund,val,cashf,fundr,teams,age,loc,industry,year)
        info = [title,rev,fund,val,cashf,fundr,teams,age,loc,industry,year]
        thewriter.writerow(info)

In [103]:
import pandas as pd
df=pd.read_csv("/content/getlatka.csv")
df

,Name,Revenue,Funding,Valuation,Cash Flow,Founder,Team Size,Age (Yrs),Location,Industry,Year
0,Coralogix,$36M,$236.5M,$1B,Even,Ariel Assaraf,163,8,United States,DevSecOps Software,2014
1,Paddle,$55M,$293.3M,$1.4B,Neg,Christian Owens,262,10,NaN,United Kingdom,2012
2,Hotjar,$25M,115,8,Even,David Darmanin,2017,8,NaN,Malta,2017
3,ClickUp,$80M,$537.5M,$4B,Neg,Zeb Evans,800,5,NaN,United States,2017
4,SecurityScorecard,$71M,$293.4M,$980M,Neg,Aleksandr Yampolskiy,350,8,NaN,United States,2014
5,Lemlist,$10M,$30M,$150M,$100K,Guillaume Moubeche,38,4,NaN,France,2019
6,Copado,$52M,$278M,$1.2B,Even,Ted Elliott,520,9,NaN,United States,2018
7,ProfitWell,$22M,$150M,91,Pos,Patrick Campbell,10,10,United States,Marketing & Advertising,2014
8,Mindee,$1.4M,$16.2M,35,Even,Jonathan Grandperrin,4,4,France,Document Management,2018
9,Cloudbeds,$30M,$248.4M,540,Even,Adam Harris,10,10,NaN,United States,2012
10,Chili Piper,$16.2M,$58M,$625M,Neg,Nicolas Vandenberghe,150,6,NaN,United States,2018
11,Hopin,$100M,$1B,$7.8B,Pos,Johnny Boufarhat,739,2,United Kingdom,Video Solution Software,2020
12,Gong,$120M,$583M,$7.3B,Neg,Amit Bendov,649,6,Amit Bendov,NaN,2016
13,Outreach,$158M,$488.7M,$4.2B,Neg,Manny Medina,1038,8,Manny Medina,NaN,2011
14,Zenefits,$100M,$584.1M,$4B,Neg,Jay Fulcher,421,9,Jay Fulcher,NaN,2013
15,Zenbusiness,$45M,$273.1M,$1.7B,Neg,Ross Buhrdorf,380,6,NaN,United States,2016
16,Acuityscheduling,$9.6M,11,15,Even,Gavin Zuchlinski,2016,15,NaN,United States,2016
17,WriterAccess,$9.4M,14,12,Even,Byron White,2010,12,NaN,United States,2010
18,"Deckrobot Inc,DeckRobot",$1.1M,$2.5M,20,Even,Tony Urban,5,5,NaN,United States,2017
19,Docsend,$9.2M,$14.7M,$165M,Even,Russ Heddleston,63,9,Russ Heddleston,NaN,2013
20,247 ai,$306M,$22M,$3.5B,$2.5M,Pv Kannan,6248,22,NaN,United States,2000
21,Freshworks,$337.8M,$1.5B,$9.1B,Neg,Girish Mathrubootham,4811,12,NaN,California,2011
22,Numerated,$26M,$27.5M,70,-$600K,Daniel O'Malley,5,5,NaN,United States,2017
23,DesignPickle,$21.1M,$249.5K,66,Pos,Russ Perry,7,7,NaN,United States,2016
24,Handshake,$20M,$23.5M,$100M,Even,Glen Coates,12,11,NaN,United States,2012

# **<center>THANK YOU**